name: Update Composer Lock

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update-composer-lock:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    - name: Install Dependencies
      run: composer update --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Commit updated composer.lock
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add composer.lock
        git commit -m "Update composer.lock"
        git push
