name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: electroverse
        options: >-
          --health-cmd="mysqladmin ping -u root -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - name: Check out code
      uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Trust Composer Public Keys
      run: |
        curl -sS https://composer.github.io/pubkeys.html | grep -o '0x[0-9A-F]\{16\}' | xargs -n 1 -I {} gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys {}
    - name: Update Composer
      run: composer self-update
    - name: Install Dependencies
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist || composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Diagnose Composer
      run: composer diagnose
    - name: Show PHP Version
      run: php -v
    - name: Show Composer Version
      run: composer --version
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Wait for MySQL to be ready
      run: |
        sudo apt-get install -y netcat
        while ! nc -z localhost 3306; do   
          echo "Waiting for MySQL...";
          sleep 1;
        done;
    - name: Create Database
      env:
        DB_CONNECTION: mysql
        DB_HOST: localhost
        DB_PORT: 3306
        DB_DATABASE: electroverse
        DB_USERNAME: root
        DB_PASSWORD: admin
      run: |
        mysql -h 127.0.0.1 -P 3306 -u root -proot -e 'SHOW DATABASES;'
    - name: Run Migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: localhost
        DB_PORT: 3306
        DB_DATABASE: electroverse
        DB_USERNAME: root
        DB_PASSWORD: admin
      run: php artisan migrate --force
    - name: Run Tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: localhost
        DB_PORT: 3306
        DB_DATABASE: electroverse
        DB_USERNAME: root
        DB_PASSWORD: admin
      run: php artisan test
