name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - name: Check out code
      uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Trust Composer Public Keys
      run: |
        curl -sS https://composer.github.io/pubkeys.html | grep -o '0x[0-9A-F]\{16\}' | xargs -n 1 -I {} gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys {}
    - name: Update Composer
      run: composer self-update
    - name: Install Dependencies
      run: |
        composer install --no-dev -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist || composer update --no-dev -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Diagnose Composer
      run: composer diagnose
    - name: Show PHP Version
      run: php -v
    - name: Show Composer Version
      run: composer --version
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Configure Cache
      run: php artisan config:cache
    - name: Run Tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: ./vendor/bin/phpunit --verbose
